### ISSUE TITLE
Database Error: unable to open database file

### ISSUE THREAD

**Issue by BeiChenStanly** [ChrisChen0904CY/CCalculator#1]
![image](https://github.com/user-attachments/assets/e5dcbb11-3899-4bb2-8a46-b298c29a6d69)
安装后一打开就是这样，在windows11-22h2 64位操作系统上

**Comment by CC-AIMI** [comment]
您好 感谢下载与反馈 请试试下载最新的v1.5.2版本 这个问题应该是出现在之前某个发布的版本中没有正确打包sql数据库的相关组件 如果依然无法打开数据库请及时通知我 另外邮件联系我会更及时地看到
